// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: task.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务阶段
type TaskPhase int32

const (
	TaskPhase_Unknown   TaskPhase = 0
	TaskPhase_Pending   TaskPhase = 1
	TaskPhase_Running   TaskPhase = 2
	TaskPhase_Paused    TaskPhase = 3
	TaskPhase_Error     TaskPhase = 4
	TaskPhase_Completed TaskPhase = 5
	TaskPhase_Deleted   TaskPhase = 6
)

// Enum value maps for TaskPhase.
var (
	TaskPhase_name = map[int32]string{
		0: "Unknown",
		1: "Pending",
		2: "Running",
		3: "Paused",
		4: "Error",
		5: "Completed",
		6: "Deleted",
	}
	TaskPhase_value = map[string]int32{
		"Unknown":   0,
		"Pending":   1,
		"Running":   2,
		"Paused":    3,
		"Error":     4,
		"Completed": 5,
		"Deleted":   6,
	}
)

func (x TaskPhase) Enum() *TaskPhase {
	p := new(TaskPhase)
	*p = x
	return p
}

func (x TaskPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskPhase) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPhase.Descriptor instead.
func (TaskPhase) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

// 任务信息
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phase         TaskPhase              `protobuf:"varint,3,opt,name=phase,proto3,enum=task.TaskPhase" json:"phase,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"` // 文件大小，单位byte
	Download      *DownloadStatus        `protobuf:"bytes,50,opt,name=Download,proto3,oneof" json:"Download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetPhase() TaskPhase {
	if x != nil {
		return x.Phase
	}
	return TaskPhase_Unknown
}

func (x *Task) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Task) GetDownload() *DownloadStatus {
	if x != nil {
		return x.Download
	}
	return nil
}

// 下载状态
type DownloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         uint64                 `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`       // 下载速度，单位byte/s
	Progress      uint64                 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // 下载进度，单位byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadStatus) Reset() {
	*x = DownloadStatus{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadStatus) ProtoMessage() {}

func (x *DownloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadStatus.ProtoReflect.Descriptor instead.
func (*DownloadStatus) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadStatus) GetSpeed() uint64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *DownloadStatus) GetProgress() uint64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\"\xa9\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x0f.task.TaskPhaseR\x05phase\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x125\n" +
	"\bDownload\x182 \x01(\v2\x14.task.DownloadStatusH\x00R\bDownload\x88\x01\x01B\v\n" +
	"\t_Download\"B\n" +
	"\x0eDownloadStatus\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x04R\x05speed\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x04R\bprogress*e\n" +
	"\tTaskPhase\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\v\n" +
	"\aRunning\x10\x02\x12\n" +
	"\n" +
	"\x06Paused\x10\x03\x12\t\n" +
	"\x05Error\x10\x04\x12\r\n" +
	"\tCompleted\x10\x05\x12\v\n" +
	"\aDeleted\x10\x06B\x06Z\x04./vob\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_proto_goTypes = []any{
	(TaskPhase)(0),         // 0: task.TaskPhase
	(*Task)(nil),           // 1: task.Task
	(*DownloadStatus)(nil), // 2: task.DownloadStatus
}
var file_task_proto_depIdxs = []int32{
	0, // 0: task.Task.phase:type_name -> task.TaskPhase
	2, // 1: task.Task.Download:type_name -> task.DownloadStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_task_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
