syntax = "proto3";
package task;
option go_package = "./vo";

// 任务信息
message Task {
  string id = 1;
  string name = 2;
  TaskPhase phase = 3;
  uint64 size = 4;  // 文件大小，单位byte
  optional Category category = 5;
  uint64 created_at = 6;  // 创建时间戳，单位秒

  optional DownloadStats download_stats = 50;
  optional UploadStats upload_stats = 51;
}

// 类别
message Category{
  string name = 1;
  string icon = 2;
}

// 任务阶段
enum TaskPhase {
  TpUnknown = 0;

  TpDownQueued = 51;
  TpDownRunning = 52;
  TpDownPaused = 53;
  TpDownFailed = 54;
  TpDownCompleted = 55;

  TpUpQueued = 101;
  TpUpRunning = 102;
  TpUpPaused = 103;
  TpUpFailed = 104;
  TpUpCompleted = 105;
}

// 下载状态
message DownloadStats {
  uint64 speed = 1;  // 速度，单位byte/s
  uint64 size = 2;  // 大小，单位byte
}

// 上传状态
message UploadStats {
  uint64 speed = 1;  // 速度，单位byte/s
  uint64 size = 2;  // 大小，单位byte
}

message ListTasksResponse {
  repeated Task tasks = 1;
}

message CreateTaskRequest {
  repeated string links = 1;  // 下载链接，至少需要存在一个链接，其他的作为备份链接
  string name = 10;
  optional string category = 11;
}

message CreateTaskResponse {
  string id = 1;
}

// 操作行为
enum Operate {
  OpUnknown = 0;
  OpDelete = 1;  // 删除
  OpResume = 2;  // 恢复上传/下载
  OpPause = 3;  // 暂停
  OpRetry = 4;  // 失败重试
}

message OperateTasksRequest {
  repeated string ids = 1;
  Operate operate = 2;
}

message HomepageResponse {
  int32 dl_count = 1;
  string dl_speed = 2;
  int32 ul_count = 3;
  string ul_speed = 4;
}

message TaskDownloadCompletedFallbackRequest {
  string category = 1;
  string name = 2;
  string hash = 3;
  string save_path = 4;
}